<a href="https://colab.research.google.com/github/AswiniSivadasan/DSA_Assignments/blob/main/Aswini_Assignment_ModelSelection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
#loading libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [63]:
# Importing the dataset
dataset = pd.read_csv('/content/titanic_dataset .csv')

In [64]:
#data preprocessing
dataset.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [35]:
dataset.shape

(891, 12)

In [36]:
dataset.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [37]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [38]:
# mean of entire dataframe
mean_value = dataset.mean()
mean_imputation = dataset.fillna(mean_value)
mean_imputation.head()

<ipython-input-38-7194d5fe67d6>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mean_value = dataset.mean()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [39]:
#filling the columns having null values with the mean
dataset['Age']=dataset['Age'].fillna(dataset['Age'].mean())
# dataset['Cabin']=dataset['Cabin'].fillna(dataset['Cabin'].mean())
# dataset['Embarked']=dataset['Embarked'].fillna(dataset['Embarked'].mean())

In [40]:
# Fill null values in 'Cabin' and 'Embarked' columns with zero
dataset['Cabin'].fillna(0, inplace=True)
dataset['Embarked'].fillna(0, inplace=True)

In [41]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [55]:
#loading libraries for KNN
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [65]:
# Drop the specified columns
dataset = dataset.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], axis=1)

# Handle Missing Values
dataset = dataset.dropna()  # Drop rows with missing values, you can also use imputation techniques

# Separate features and target
X = dataset.drop('Survived', axis=1)
y = dataset['Survived']

# Data Preprocessing
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [66]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  714 non-null    int64
 1   Survived     714 non-null    int64
 2   Pclass       714 non-null    int64
 3   Age          714 non-null    float64
 4   SibSp        714 non-null    int64
 5   Parch        714 non-null    int64
 6   Fare         714 non-null    float64
dtypes: float64(2), int64(5)
memory usage: 44.6 KB

In [67]:
# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [69]:
# Standardizing the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [70]:
# Creating and fitting the KNN model
knn = KNeighborsClassifier(n_neighbors=5)  # You can change the number of neighbors
knn.fit(X_train, y_train)

# Predicting with the test set
y_pred = knn.predict(X_test)

# Evaluating the model
accuracy = knn.score(X_test, y_test)
print(f"Accuracy of the KNN model: {accuracy}")

Accuracy of the KNN model: 0.6433566433566433

In [71]:
from sklearn.svm import SVC

# Create SVM model
svm = SVC(kernel='linear')
svm.fit(X_train, y_train)

# Predict
svm_predictions = svm.predict(X_test)

# Calculate accuracy
svm_accuracy = accuracy_score(y_test, svm_predictions)
print("SVM Accuracy:", svm_accuracy)

SVM Accuracy: 0.6783216783216783

In [72]:

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold

# Creating the KNN model
knn_model = KNeighborsClassifier()

# K-Fold Cross Validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
knn_scores = cross_val_score(knn_model, X, y, cv=kfold)

# Average accuracy score for KNN model
knn_avg_accuracy = knn_scores.mean()
print("Average Accuracy of KNN Model:", knn_avg_accuracy)

Average Accuracy of KNN Model: 0.6891236306729265

In [73]:
from sklearn.svm import SVC
# Creating the SVM model
svm_model = SVC()

# Stratified K-Fold Cross Validation
stratified_kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
svm_scores = cross_val_score(svm_model, X, y, cv=stratified_kfold)

# Average accuracy score for SVM model
svm_avg_accuracy = svm_scores.mean()
print("Average Accuracy of SVM Model:", svm_avg_accuracy)

Average Accuracy of SVM Model: 0.728169014084507